language: node_js
node_js:
- lts/*
deploy:
  provider: heroku
  api_key:
    secure: IXrrOLdvbesVPt0KkdglXFn865y27rXgAq9pa/p/+w4D6mxVSJ9NZKI0Q+npL3jrSPRCHXwubTlP1MCtE1cVrQ35J/1ys02QfszPQCxvjLYeHuaeVFrq4R0ju3loIL0Hm5KVlvyrpd4Lykj41Yo0HNLla0eB9BHNogp0gAz6DSAosNPurqZ6amS0P47yWPvBdpxiiz75CiNu1NbkYdABR3NjacTYFIPRkkI/L0nd77P7NDvEokFNjNVd2E5C02gG5edmKY1rtRLHF6++mIViP1CATo69Blj5lSkcdfthbbEwgb80GeYdtlO+pIFDgKvsO4zPWZLoluIWmbAUv/BowQQ0YXum0UhCfMhr9HJCKTSuvHobSbbGepRmgbQRk8fQuMxqcuXvLYIkIZvDm+irGhkuIKo0D04L6+QdaO0hPWpjVmOKhm/x7Jp0ffgVmc0ERINYbaUDCd8I79ZEd70Obzb8ruW9rPCehum/ZoAYlH2vHQJOdz9RIDZkFQS3KEHsw2DyewoBnvXHVPgyPb3RRMWzpWpdA9v0C98cvd293OQIf38NnA4xKr5nj8TeGK4q0vv2erktI771+yr08SWqZJ4KiD8S0ySRsEHS1sBv8JJrr+v7JscGKH1+9EZdqOWS9AWibH/blJPqVXCZDF3EESQLYgh4f0DN3WXgqEFL+Iw=
