language: node_js
node_js:
- lts/*
deploy:
  provider: heroku
  api_key:
    secure: zwD8CjWQUvD57UbmnoJPR8iUi5IgJYDwjCy7aUNAG0nxSmgvIK7hTPqagvpH/8PaPA1NVR+62E7mN14e4aPIrUHTchHuS1ViBGTQ5L4fbXJj8DpBA34kEiQ9OO7tlO9LlvFJifst7gszr8nOJwdBOH9WFQTwhx2caR0gyeTYpN3RgvOWbQ98f6YPnlWkD43ZJgNM4MToM/igsVdQ9x04JOTNzbBXERwb9ms3y69vC9svU/Vai5is6w4N3XsAuodIOdn+9y8lD8E+ppvbY9NFMDqlQlozmxMCVQMNpA18alrtgAm1q+2gVp+Tn9Yg0oY0xv3OxJhcI7cOg1eZVBb3yKFTeep7C9Pp65lKaKtOO8JE6/klb6aCOTmaduwPzic3n7rBIutGRifdjNg5ITmP9XamG7ucZhCPfnXZKwqRYKB3QpJaHNlpRWtwLe0/J00VcVu2Oq/yd11LAK81AwIUwUHxi8ge/KraSEJidfv9g/kO8LotD2iosk2rETzgUCwjSBUHhLmPcljXtcbZzI8FcmeJ1Q2Peea241yCNiAivgn6Lc4v4r/xOCRSwsRsE//XEeP0jLJWmvmJS47W4q4QqbDOGmPR6MoorZdgM2gNlq59PXV7qbv864oqK6cApbFHYlWcIQ9Ji0gVfr9bNldYCAWvEIQViVsFUSiEZIhRgi4=
